# Generated by Django 5.2.5 on 2025-08-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(help_text="Введите место выполнения", max_length=255, verbose_name="Место"),
                ),
                ("time", models.DateTimeField(help_text="Введите время начала", verbose_name="Время")),
                (
                    "action",
                    models.CharField(help_text="Введите действия привычки", max_length=255, verbose_name="Действие"),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если привычка является приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Введите периодичность выполнения привычки в днях",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите вознаграждение за выполнение привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        help_text="Введите приблизительное время на выполнение привычки",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если привычку можно публиковать",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Введите ID создателя привычки (пользователя)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите ID связанной привычки, если она есть",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="chats.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
